; This file was automatically generated by ScriptHubImporter.py
this.EllywickDeckOfManyThingsHandler.currentMonsterKills := New GameObjectStructure(this.EllywickDeckOfManyThingsHandler,"Int", [0xcc])
this.EllywickDeckOfManyThingsHandler.cardsInHand := New GameObjectStructure(this.EllywickDeckOfManyThingsHandler,"List", [0x98])
this.EllywickDeckOfManyThingsHandler.cardsInHand._CollectionValType := "CrusadersGame.Effects.EllywickDeckOfManyThingsHandler.Card"
this.EllywickDeckOfManyThingsHandler.cardsInHand.CardType := New GameObjectStructure(this.EllywickDeckOfManyThingsHandler.cardsInHand,"Int", [0x48])
this.EllywickDeckOfManyThingsHandler.tempProbabilityMap := New GameObjectStructure(this.EllywickDeckOfManyThingsHandler,"Dict", [0xa8])
this.EllywickDeckOfManyThingsHandler.tempProbabilityMap._CollectionKeyType := "CrusadersGame.Effects.EllywickDeckOfManyThingsHandler.CardType"
this.EllywickDeckOfManyThingsHandler.tempProbabilityMap._CollectionValType := "System.Single"
this.EllywickDeckOfManyThingsHandler.ultimateActive := New GameObjectStructure(this.EllywickDeckOfManyThingsHandler,"Char", [0xc0])
this.EllywickDeckOfManyThingsHandler.controller := New GameObjectStructure(this.EllywickDeckOfManyThingsHandler,"Int", [0x10])
this.EllywickDeckOfManyThingsHandler.controller.GameInstance_k__BackingField := New GameObjectStructure(this.EllywickDeckOfManyThingsHandler.controller,"Int", [0x10])
this.EllywickDeckOfManyThingsHandler.controller.GameInstance_k__BackingField.StatHandler := New GameObjectStructure(this.EllywickDeckOfManyThingsHandler.controller.GameInstance_k__BackingField,"Int", [0x50])
this.EllywickDeckOfManyThingsHandler.controller.GameInstance_k__BackingField.StatHandler.EllywickGemMult := New GameObjectStructure(this.EllywickDeckOfManyThingsHandler.controller.GameInstance_k__BackingField.StatHandler,"Quad", [0x2c0])
